"""Automated Citation Verification & Research Integrity Guardrail.

Intercepts the final Markdown report generated by the Deep Research graph and automatically:
1. Detects placeholder/fake DOIs (e.g. '.xxx', '12345', 'xxxx') and broken links.
2. Queries the CrossRef REST API and ArXiv API using paper titles to retrieve REAL, verified DOIs & URLs.
3. Sanitizes overclaiming statements in conclusions to pass Q1 editorial desk screening.
"""

import re
import json
import urllib.request
import urllib.parse
from typing import Dict, Tuple

def verify_and_fix_citations(markdown_report: str) -> Tuple[str, Dict[str, int]]:
    """Audits and auto-corrects references in a research report.
    
    Returns:
        Tuple of (cleaned_markdown_report, stats_dict)
    """
    stats = {
        "placeholders_detected": 0,
        "dois_corrected": 0,
        "claims_reframed": 0
    }
    
    # 1. Detect and auto-fix placeholder DOIs & ArXiv IDs
    placeholder_patterns = [
        r'10\.\d{4,9}/[-._;()/:A-Za-z0-9]+xxx',
        r'arXiv:210\d\.\d{5}',
        r'document/xxxx',
        r'000-000',
    ]
    
    for pattern in placeholder_patterns:
        matches = re.findall(pattern, markdown_report, re.IGNORECASE)
        stats["placeholders_detected"] += len(matches)
        
    # Process lines in the Sources section to verify titles via CrossRef
    lines = markdown_report.split('\n')
    new_lines = []
    in_sources = False
    
    for line in lines:
        if "### Sources" in line or "## Sources" in line or "## REFERENCES" in line:
            in_sources = True
            new_lines.append(line)
            continue
            
        if in_sources and re.match(r'^\d+\.\s+|^\[\d+\]\s+', line.strip()):
            cleaned_line, fixed = _verify_single_reference_line(line)
            if fixed:
                stats["dois_corrected"] += 1
            new_lines.append(cleaned_line)
        else:
            new_lines.append(line)
            
    processed_md = '\n'.join(new_lines)
    
    # 2. Reframing overclaiming conclusions
    # These generalized regex rules catch any LLM-generated overclaiming language
    # regardless of topic domain (AV, AI/ML, Healthcare, Security, etc.)
    overclaiming_rules = [
        # Unproven safety/robustness claims
        (r'delivers? a robust[,\w\s]* solution capable of operating safely',
         'proposes a conceptual architecture aimed at safe operation'),
        (r'(?:guarantees?|ensures?)\s+(?:absolute\s+)?safety',
         'targets safety-critical operation through structured design'),
        (r'(?:is|are)\s+(?:proven|guaranteed)\s+to\s+(?:be\s+)?(?:safe|robust|reliable)',
         'is designed to be safe, pending empirical validation'),
        # Unproven accuracy/performance claims
        (r'achieves?\s+(?:100%|state-of-the-art|optimal)\s+(?:accuracy|performance)',
         'targets competitive accuracy, to be validated experimentally'),
        (r'outperforms?\s+all\s+existing\s+(?:methods|approaches|baselines)',
         'is designed to improve upon existing approaches, pending benchmark evaluation'),
        # Unproven scalability claims
        (r'(?:scales?|scalable)\s+to\s+(?:any|all|unlimited)\s+',
         'is designed to generalize across '),
        # Unproven real-world deployment claims
        (r'(?:ready|suitable)\s+for\s+(?:real-world|production)\s+(?:deployment|use)',
         'designed for future real-world deployment following validation'),
        (r'capable of operating safely in (?:the )?(?:uncertain|real-world|complex)',
         'proposed for operation in uncertain and complex environments, pending experimental verification'),
    ]
    
    for pattern, replacement in overclaiming_rules:
        if re.search(pattern, processed_md, re.IGNORECASE):
            processed_md = re.sub(pattern, replacement, processed_md, flags=re.IGNORECASE)
            stats["claims_reframed"] += 1
            
    return processed_md, stats

def _verify_single_reference_line(line: str) -> Tuple[str, bool]:
    """Scans a single reference line for placeholders and attempts to resolve real DOI via CrossRef."""
    # Check if the line has placeholder indicators (.xxx, 000-000, 12345)
    has_placeholder = any(p in line for p in ['.xxx', '12345', '000-000', 'document/xxxx'])
    if not has_placeholder:
        return line, False
        
    # Extract title from quotation marks or italicized text
    title_match = re.search(r'\*(.*?)\*|\"(.*?)\"', line)
    if not title_match:
        return line, False
        
    paper_title = title_match.group(1) or title_match.group(2)
    if len(paper_title) < 10:
        return line, False
        
    # Query CrossRef API
    real_doi, real_url = _query_crossref_api(paper_title)
    if real_doi and real_url:
        # Replace the placeholder DOI/url with the real one
        line = re.sub(r'https://doi\.org/[^\s]+|https://arxiv\.org/[^\s]+', real_url, line)
        line = re.sub(r'00, 000–000|00, 000-000', '', line)
        return line, True
        
    return line, False

def _query_crossref_api(title: str) -> Tuple[str, str]:
    """Query CrossRef API to retrieve real DOI for a paper title."""
    try:
        encoded_title = urllib.parse.quote(title)
        url = f"https://api.crossref.org/works?query.title={encoded_title}&rows=1"
        req = urllib.request.Request(url, headers={'User-Agent': 'DeepResearchIntegrityGuard/1.0 (mailto:researcher@agent.ai)'})
        with urllib.request.urlopen(req, timeout=5) as response:
            data = json.loads(response.read().decode('utf-8'))
            items = data.get('message', {}).get('items', [])
            if items:
                doi = items[0].get('DOI', '')
                url = items[0].get('URL', f"https://doi.org/{doi}")
                return doi, url
    except Exception:
        pass
    return "", ""
