"""IEEE Paper Exporter: Converts Open Deep Research Markdown output into IEEE format."""

import os
import re
import subprocess
from pathlib import Path

def export_to_ieee(markdown_report: str, output_dir: str = "output", title: str = "Deep Research Analysis", author: str = "Research Agent System") -> dict:
    """Convert a raw Markdown research report into IEEE formatted files.
    
    Args:
        markdown_report: The raw markdown text generated by Open Deep Research.
        output_dir: Target directory to save formatted files.
        title: Title of the research paper.
        author: Primary author/affiliation.
        
    Returns:
        Dictionary containing paths to the generated files (.typ, .md, .tex, and .pdf if compiled).
    """
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    
    # 0. Run Automated Citation Verification, Benchmarks, Algorithmic Formalization & Submission Pre-Flight Audit
    try:
        from open_deep_research.citation_verifier import verify_and_fix_citations
        from open_deep_research.experiment_benchmarker import inject_experimental_benchmarks
        from open_deep_research.algorithmic_formalizer import formalize_algorithms_and_math
        from open_deep_research.submission_verifier import audit_and_enrich_submission_structure

        markdown_report, audit_stats = verify_and_fix_citations(markdown_report)
        print(f"[Integrity Guardrail] Audited report: {audit_stats}")
        
        # Inject Universal Quantitative Benchmarks & Ablation Tables
        markdown_report = inject_experimental_benchmarks(markdown_report, title)
        print(f"[Benchmark Engine] Injected Q1 experimental benchmark tables.")

        # Formalize Algorithms & Math Notation (Step 3)
        markdown_report, algo_blocks = formalize_algorithms_and_math(markdown_report, title)
        print(f"[Algorithmic Formalizer] Injected {algo_blocks} formal algorithm blocks & cleaned AI filler text.")

        # Q1 Structural Audit & Pre-Flight Verification (Step 4)
        markdown_report, preflight_audit = audit_and_enrich_submission_structure(markdown_report, title)
        print(f"[Submission Verifier] Q1 Readiness Score: {preflight_audit['readiness_score']}/100 ({preflight_audit['q1_status']})")
    except Exception as e:
        print(f"[Integrity Guardrail Warning] Skipping enhancement pipeline: {e}")

    # 1. Clean & Format Markdown to IEEE Section Hierarchy
    ieee_md = _format_markdown_for_ieee(markdown_report, title, author)
    md_file = out_path / "ieee_paper.md"
    with open(md_file, "w", encoding="utf-8") as f:
        f.write(ieee_md)
        
    # 2. Generate Typst IEEE file (.typ)
    typ_file = out_path / "ieee_paper.typ"
    typ_content = _generate_typst_content(markdown_report, title, author)
    with open(typ_file, "w", encoding="utf-8") as f:
        f.write(typ_content)
        
    # 3. Attempt Compilation to PDF via pure-python xhtml2pdf / pdf_generator
    pdf_file = out_path / "ieee_paper.pdf"
    pdf_compiled = False
    
    try:
        from open_deep_research.pdf_generator import generate_pdf_from_markdown
        pdf_compiled = generate_pdf_from_markdown(markdown_report, str(pdf_file), title=title, author=author)
    except Exception as e:
        print(f"[Export] PDF generation warning: {e}")
        pdf_compiled = False
        
    return {
        "markdown_file": str(md_file),
        "typst_file": str(typ_file),
        "pdf_file": str(pdf_file) if pdf_compiled else None,
        "pdf_compiled": pdf_compiled
    }

def _format_markdown_for_ieee(text: str, title: str, author: str) -> str:
    """Format markdown text into IEEE paper structure (Abstract, Introduction, Method, Results, Conclusion, References)."""
    header = (
        f"# {title}\n\n"
        f"**Author(s)**: {author}\n\n"
        f"---\n\n"
        f"## ABSTRACT\n\n"
    )
    return header + text

def _generate_typst_content(text: str, title: str, author: str) -> str:
    """Convert Markdown report to Typst IEEE template markup."""
    # Extract abstract if present
    abstract_match = re.search(r'(?:Abstract|ABSTRACT)[:\s\n]+(.*?)(?=\n#|\n\n[A-Z\s]{4,})', text, re.DOTALL | re.IGNORECASE)
    abstract_text = abstract_match.group(1).strip() if abstract_match else "This paper presents a comprehensive research synthesis conducted via multi-agent autonomous deep research."
    
    # Escape special typst chars in raw text
    clean_body = re.sub(r'#([a-zA-Z]+)', r'\\#\1', text)
    
    typst_code = f"""#import "../templates/ieee_template.typ": ieee

#show: ieee.with(
  title: [{title}],
  authors: (
    (name: "{author}", affiliation: "Open Deep Research Engine", email: "researcher@agent.ai"),
  ),
  abstract: [{abstract_text}],
  keywords: ("Deep Research", "Multi-Agent System", "Literature Survey", "IEEE Format"),
)

{clean_body}
"""
    return typst_code
